services:
  next:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - APP_ENV=development
      - CI=true
    command: ["pnpm", "run", "dev"]